function rirs = generateRirs(setup)
% Direct component only
    rirs.direct=rir_generator(setup.room.soundSpeed,setup.signal.sampFreq,...
        setup.room.receivPos,setup.room.sourcePos,setup.room.dimensions,...
        setup.room.T60,setup.rirGen.length,setup.rirGen.micType...
        ,0,3,[]);
% All reflections including the direct path component
    rirs.all=rir_generator(setup.room.soundSpeed,setup.signal.sampFreq,...
        setup.room.receivPos,setup.room.sourcePos,setup.room.dimensions,...
        setup.room.T60,setup.rirGen.length,setup.rirGen.micType...
        ,setup.rirGen.order,2,[]);
%   All reflections excl. direct path component
    rirs.reflec=rirs.all-rirs.direct;
end
